language: cpp
compiler:
  - clang
env:
  - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
before_install:
  - sudo add-apt-repository -y ppa:kalakris/cmake
  - sudo add-apt-repository -y ppa:codegear/release
  - sudo apt-get update -qq
  - sudo apt-get install -y gyp libgtest-dev xpra xserver-xorg-video-dummy libglew-dev libbox2d-dev libglm-dev xorg-dev libglu1-mesa-dev cmake premake4 xvfb
  - cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib ; cd -
  - git clone https://github.com/glfw/glfw
  - cd glfw && mkdir build && cd build && cmake .. -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF -DBUILD_SHARED_LIBS=ON && make && sudo make install && cd ../../
  - hg clone https://bitbucket.org/SpartanJ/soil2
  - cd soil2 && premake4 gmake && cd make/linux && make -f soil2-static-lib.make config=release && sudo cp -rv ../../src/SOIL2/ /usr/local/include && sudo cp ../../lib/linux/libsoil2.a /usr/local/lib && cd ../../../
  - sudo mv /usr/lib/libbox2d.so /usr/lib/libBox2D.so
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - pwd
  - which sh
script: "cd test && sh ./.travis_build.sh""
branches:
  only:
    - develop
